#!/bin/bash
set -e
cd `dirname $0`

PROJECT_ID=`gcloud config get-value project --configuration tech-lunch`
INCOMING_WEB_HOOK=https://hooks.slack.com/services/xxxxxxxxx/xxxxxxxxx/xxxxxxxxxxxxxxxx

cp ./dist/index.js ./index.js
cp ../../gcloud-configs/tech-lunch.json ./tech-lunch.json

gcloud functions deploy notifyScreenCaptureToSlack \
  --entry-point notifyScreenCaptureToSlack \
  --region asia-northeast1 \
  --runtime nodejs12 \
  --trigger-resource tech-lunch \
  --trigger-event google.storage.object.finalize \
  --timeout 20 \
  --memory 128MB \
  --set-env-vars PROJECT_ID=$PROJECT_ID,INCOMING_WEB_HOOK=$INCOMING_WEB_HOOK,GOOGLE_APPLICATION_CREDENTIALS=./tech-lunch.json \
  --max-instances 1

rm ./index.js
rm ./tech-lunch.json
